argoWorkflows:
  enabled: true
  repository:
    version: 0.24.1
  config:
    singleNamespace: false
    server:
      enabled: true
      extraArgs: ["--auth-mode=client"]
    workflow:
      serviceAccount:
        create: true 
        name: "argo-workflows" 
      rbac:
        create: true 

argoEvents:
  enabled: true
  repository:
    version: 2.2.0
  config:
    singleNamespace: false
    securityContext:
      runAsNonRoot: true
      runAsUser: null


argocdConfig:
  generators: []
  project:
    create: false
    name: default
