apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: helm-publish
  namespace: argo
spec:
  entrypoint: init-dag
    volumes:
  - name: workdir
    emptyDir: {}
  templates:
  - name: init-dag
    dag:
      tasks:
      - name: helm-test
        template: helm-test

#      - name: D
#        depends: "B && C"
#        template: coinflip

  - name: helm-test
    container:
      image: alpine/helm
      command: [sh, -c]
      args: ["helm create \"/workspace/mychart\""]
      volumeMounts:
      - name: workdir
        mountPath: /workspace